# Generated by Django 3.2.11 on 2022-01-17 11:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('HeroImage', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='Entre your image'))])), ('posts', wagtail.core.blocks.StructBlock([('post', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title', required=False)), ('body', wagtail.core.blocks.TextBlock(default='RichText', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))]),
        ),
    ]
