# Generated by Django 3.2.11 on 2022-01-17 12:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_pages', '0002_alter_aboutpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('posts', wagtail.core.blocks.StructBlock([('post', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title', required=False)), ('body', wagtail.core.blocks.TextBlock(default='RichText', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('HeroImage', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title', required=False)), ('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='Entre your image'))]))]),
        ),
    ]
